/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PlaysRouteImport } from './routes/plays'
import { Route as MeasureRouteImport } from './routes/measure'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CadencesRouteImport } from './routes/cadences'
import { Route as AddProspectRouteImport } from './routes/add-prospect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunPlayNameRouteImport } from './routes/run.$playName'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysRoute = PlaysRouteImport.update({
  id: '/plays',
  path: '/plays',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasureRoute = MeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CadencesRoute = CadencesRouteImport.update({
  id: '/cadences',
  path: '/cadences',
  getParentRoute: () => rootRouteImport,
} as any)
const AddProspectRoute = AddProspectRouteImport.update({
  id: '/add-prospect',
  path: '/add-prospect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunPlayNameRoute = RunPlayNameRouteImport.update({
  id: '/run/$playName',
  path: '/run/$playName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-prospect': typeof AddProspectRoute
  '/cadences': typeof CadencesRoute
  '/inbox': typeof InboxRoute
  '/measure': typeof MeasureRoute
  '/plays': typeof PlaysRoute
  '/queue': typeof QueueRoute
  '/receipts': typeof ReceiptsRoute
  '/setup': typeof SetupRoute
  '/run/$playName': typeof RunPlayNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-prospect': typeof AddProspectRoute
  '/cadences': typeof CadencesRoute
  '/inbox': typeof InboxRoute
  '/measure': typeof MeasureRoute
  '/plays': typeof PlaysRoute
  '/queue': typeof QueueRoute
  '/receipts': typeof ReceiptsRoute
  '/setup': typeof SetupRoute
  '/run/$playName': typeof RunPlayNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-prospect': typeof AddProspectRoute
  '/cadences': typeof CadencesRoute
  '/inbox': typeof InboxRoute
  '/measure': typeof MeasureRoute
  '/plays': typeof PlaysRoute
  '/queue': typeof QueueRoute
  '/receipts': typeof ReceiptsRoute
  '/setup': typeof SetupRoute
  '/run/$playName': typeof RunPlayNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-prospect'
    | '/cadences'
    | '/inbox'
    | '/measure'
    | '/plays'
    | '/queue'
    | '/receipts'
    | '/setup'
    | '/run/$playName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-prospect'
    | '/cadences'
    | '/inbox'
    | '/measure'
    | '/plays'
    | '/queue'
    | '/receipts'
    | '/setup'
    | '/run/$playName'
  id:
    | '__root__'
    | '/'
    | '/add-prospect'
    | '/cadences'
    | '/inbox'
    | '/measure'
    | '/plays'
    | '/queue'
    | '/receipts'
    | '/setup'
    | '/run/$playName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddProspectRoute: typeof AddProspectRoute
  CadencesRoute: typeof CadencesRoute
  InboxRoute: typeof InboxRoute
  MeasureRoute: typeof MeasureRoute
  PlaysRoute: typeof PlaysRoute
  QueueRoute: typeof QueueRoute
  ReceiptsRoute: typeof ReceiptsRoute
  SetupRoute: typeof SetupRoute
  RunPlayNameRoute: typeof RunPlayNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays': {
      id: '/plays'
      path: '/plays'
      fullPath: '/plays'
      preLoaderRoute: typeof PlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measure': {
      id: '/measure'
      path: '/measure'
      fullPath: '/measure'
      preLoaderRoute: typeof MeasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadences': {
      id: '/cadences'
      path: '/cadences'
      fullPath: '/cadences'
      preLoaderRoute: typeof CadencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-prospect': {
      id: '/add-prospect'
      path: '/add-prospect'
      fullPath: '/add-prospect'
      preLoaderRoute: typeof AddProspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$playName': {
      id: '/run/$playName'
      path: '/run/$playName'
      fullPath: '/run/$playName'
      preLoaderRoute: typeof RunPlayNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddProspectRoute: AddProspectRoute,
  CadencesRoute: CadencesRoute,
  InboxRoute: InboxRoute,
  MeasureRoute: MeasureRoute,
  PlaysRoute: PlaysRoute,
  QueueRoute: QueueRoute,
  ReceiptsRoute: ReceiptsRoute,
  SetupRoute: SetupRoute,
  RunPlayNameRoute: RunPlayNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
