import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PLAY_DESCRIPTIONS } from "../packages/plays/src/descriptions.ts";

const path = fileURLToPath(new URL("../docs/plays.md", import.meta.url));
const guide = `# Choosing a play

<!-- Generated by scripts/generate-play-guide.ts. Edit packages/plays/src/descriptions.ts. -->

Choose by buyer situation. Set your founder profile and product positioning in Setup. Email needs a deliverable address and configured sender; other channels need their corresponding contact details. Preview drafts before sending.

The dashboard shows current cadence timing and optional direct mail. Live API runs can send; manual channels require you to post and confirm. Outputs below describe outreach, not completed sales outcomes.

${Object.entries(PLAY_DESCRIPTIONS)
  .map(
    ([name, d]) =>
      `## ${name}\n\n- **When to use it:** ${d.whenToUse}\n- **What it does:** ${d.actions}\n- **What you need:** ${d.requires}\n- **What it produces:** ${d.produces}\n`,
  )
  .join("\n")}`;
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8") !== guide) {
    console.error("Play guide is stale. Run bun run scripts/generate-play-guide.ts");
    process.exitCode = 1;
  }
} else writeFileSync(path, guide);
